services:
  postgres:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_DB: skala_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - shop-postgres-data:/var/lib/postgresql

volumes:
  shop-postgres-data:
